/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Tobi' at '22.06.16 15:00' with Gradle 2.14
 *
 * @author Tobi, @date 22.06.16 15:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
